version: "3.3"

services:

   rhcertification:
     image: ajeetraina/redhatcert
     network_mode: "host"
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
     privileged: true
     restart: always
     command: sh -c "/usr/sbin/init" 
